# Generated by Django 5.0.1 on 2024-01-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_expense_is_active_expense_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.CharField(max_length=90),
        ),
    ]
